#!/bin/bash
set -euo pipefail

run() {
  local IFS
  IFS=' '
  echo >&2 "+ $*"
  "$@"
}

usage() {
  cat >&2 <<EOM
usage: $0

Unlock all luks partitions on a system using cryptsetup luksOpen.
EOM
}

case "${1-}" in
  -h|--help)
    usage
    exit 0
    ;;
esac

if [ "$(id -u)" -ne 0 ]; then
  set -x
  exec sudo "$0" "$@"
fi

for uuid in $(lsblk -r -o fstype,uuid | grep ^crypto_LUKS | cut -f2 -d' '); do
  echo "Decrypting partition with UUID $uuid:"
  run lsblk -o name,size,fstype,partlabel,label,uuid "/dev/disk/by-uuid/$uuid"

  run cryptsetup luksOpen "/dev/disk/by-uuid/$uuid" "luks-$uuid"
done

echo 'All done'

